/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.0-22-g549430e14d-20230605"
#endif /* AVUTIL_FFVERSION_H */
